version: "3.8"
services:
  app:
    build: app/
    ports:
      - 5000:5000
    volumes:
      - ./extracted_data:/app/extracted_data
      - ./app/converted_text:/app/converted_text
    command: python3 ./app.py





